# Defines our composer file version
version: "2.2"
# Define our services
services:
  # build for backend server
  # Redis service
  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
  app:
    build:
      dockerfile: Dockerfile.development
      context: .
    volumes:
      - ./dist:/app/dist
      # for public files
      - ./public:/app/public
      - ./nodemon.json:/app/nodemon.json
    # The name of our node app container
    container_name: test2brains
    # Restarts our node app whenever it fails
    restart: always
    # Exposes the necessary ports that our node app uses
    ports:
      - "3000:3000"
    # All the services our node app will link to -
    # which in our case is only mongo
    # You can other services such as a Redis
    links:
      - redis
    command: ["nodemon", "dist/app.js"]