FROM node:8

RUN mkdir /app
WORKDIR /app

COPY ./package.json /app/package.json
COPY ./brains-78452-3aa52b2692ad.json .

RUN npm install && \
    npm i -g nodemon && \
    npm i -g typescript

ENV NODE_ENV=development

EXPOSE 3000